import{S as j,N as S}from"./assets/vendor-VH5JPVsm.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function l(t){if(t.ep)return;t.ep=!0;const i=o(t);fetch(t.href,i)}})();const L=document.querySelector(".js-btn-burger-menu"),E=document.querySelector(".js-close-menu"),m=document.querySelector(".js-burger-menu"),q=document.querySelectorAll(".js-menu-link"),w=document.querySelector(".js-logo");function k(){m.classList.add("active"),m.style.visibility="visible",document.body.classList.add("no-scroll")}function f(){m.classList.remove("active"),document.body.classList.remove("no-scroll"),setTimeout(()=>{m.style.visibility="hidden"},300)}L.addEventListener("click",k);E.addEventListener("click",f);document.addEventListener("click",e=>{!m.contains(e.target)&&!L.contains(e.target)&&f()});document.addEventListener("keydown",e=>{e.key==="Escape"&&f()});q.forEach(e=>{e.addEventListener("click",f)});w.addEventListener("click",f);document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("gallery-container"),s=10,o="gallery/thumbs/",l="gallery/full/",t=".jpeg";for(let i=1;i<=s;i++){const n=document.createElement("div");n.classList.add("swiper-slide");const r=document.createElement("a");r.href=`${l}${i}${t}`,r.setAttribute("data-fancybox","gallery"),r.setAttribute("data-caption",`foto ${i}`);const u=document.createElement("img");u.src=`${o}${i}${t}`,u.alt=`Gallery imeges ${i}`,r.appendChild(u),n.appendChild(r),e.appendChild(n)}new j(".mySwiper",{loop:!0,slidesPerView:1,spaceBetween:10,pagination:!1,speed:800,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},autoplay:{delay:3e3,disableOnInteraction:!1},breakpoints:{1280:{slidesPerView:3,spaceBetween:30}}}),S.bind("[data-fancybox='gallery']",{})});const $={big:{title:"ВЕЛИКИЙ РЕСТОРАН",info:`
      <p>290 м², до 120 гостей</p>`,text:"Велика зала з гримеркою, баром, простором для сцени, танців і банкету.",capacity:{theatre:"100 гостей",classroom:"60 гостей",conference:"40 гостей",uShape:"50 гостей",banquet:"80 гостей"},images:["./big/1.jpg","./big/2.jpg","./big/3.jpg","./big/4.jpg","./big/5.jpg","./big/6.jpg"]},small:{title:"МАЛИЙ РЕСТОРАН",info:`
      <p>180 м², до 60 гостей</p>
    `,text:"Зала з гримеркою, баром, каміном, терасою та зоною для нетворкінгу біля вогнища.",capacity:{theatre:"60 гостей",classroom:"40 гостей",conference:"36 гостей",uShape:"30 гостей",banquet:"50 гостей"},images:["./small/1.jpg","./small/2.jpg","./small/3.jpg","./small/4.jpg","./small/5.jpg","./small/6.jpg"]},banquetroom:{title:"БАНКЕТНА КІМНАТА",info:`
      <p>50 м², до 25 гостей</p>
    `,text:"Закрита частина ресторану з окремим входом, терасою та зоною для вечірнього багаття.",capacity:{theatre:"30 гостей",classroom:"20 гостей",conference:"25 гостей",uShape:"15 гостей",banquet:"25 гостей"},images:["./banquet/1.jpg","./banquet/2.jpg","./banquet/3.jpg","./banquet/4.jpg","./banquet/5.jpg","./banquet/6.jpg"]},lobi:{title:"ЛОБІ ГОТЕЛЮ",info:`
      <p>160 м², до 50 гостей</p>
    `,text:"Ми повністю закриваємо крило готелю, щоб нічого не відволікало гостей від події.",capacity:{theatre:"50 гостей",banquet:"30 гостей"},images:["./lobi/1.jpg","./lobi/2.jpg","./lobi/3.jpg","./lobi/4.jpg","./lobi/5.jpg"]},pool:{title:"БАСЕЙН У ЛІСІ",info:`
      <p>площа палуби — 4500 м², до 300 гостей</p>
    `,text:"Великий басейн з видом на річку та ліс, власним баром, екраном для презентацій або кіно.",images:["./pool/1.jpg","./pool/2.jpg","./pool/3.jpg","./pool/4.jpg","./pool/5.jpg","./pool/6.jpg","./pool/7.jpg"]},terrasa:{title:"ТЕРАСА НАД ВОДОЮ",info:`
      <p>240 м², до 60 гостей</p>
    `,text:"Затишна локація з видом на ліс і річку для естетичних банкетів або для активного відпочинку на каяках, cапах чи катері.",capacity:{theatre:"40 гостей",conference:"25 гостей",banquet:"50 гостей"},images:["./terrasa/1.jpg","./terrasa/2.jpg","./terrasa/3.jpg","./terrasa/4.jpg"]}},c=document.getElementById("location-modal"),y=c.querySelector(".slider"),x=c.querySelector(".modal-title"),_=c.querySelector(".modal-info"),C=c.querySelector(".modal-text"),v=c.querySelector(".modal-capacity");let d=[],a=0;function M(e){return{theatre:"Theatre",classroom:"Classroom",conference:"Conference",uShape:"U-shape",banquet:"Banquet"}[e]||e}document.querySelectorAll(".btn-location").forEach(e=>{e.addEventListener("click",()=>{const s=e.closest("li").dataset.location,o=$[s];o&&(x.textContent=o.title,_.innerHTML=o.info,C.textContent=o.text,o.capacity?v.innerHTML=Object.entries(o.capacity).map(([l,t])=>`<p><strong>${M(l)}:</strong> ${t}</p>`).join(""):v.innerHTML="",y.innerHTML=o.images.map((l,t)=>`<div class="slide ${t===0?"active":""}">
            <img src="${l}" alt="${o.title} фото ${t+1}" />
          </div>`).join(""),d=y.querySelectorAll(".slide"),a=0,c.classList.add("active"),P())})});c.querySelector(".modal-close").addEventListener("click",()=>{c.classList.remove("active")});c.addEventListener("click",e=>{e.target===c&&c.classList.remove("active")});const g=e=>{d.forEach(s=>s.classList.remove("active")),d[e].classList.add("active")};c.querySelector(".next").addEventListener("click",()=>{d.length&&(a=(a+1)%d.length,g(a))});c.querySelector(".prev").addEventListener("click",()=>{d.length&&(a=(a-1+d.length)%d.length,g(a))});document.addEventListener("keydown",e=>{c.classList.contains("active")&&(e.key==="ArrowRight"&&(a=(a+1)%d.length,g(a)),e.key==="ArrowLeft"&&(a=(a-1+d.length)%d.length,g(a)),e.key==="Escape"&&c.classList.remove("active"))});function P(){let e=0,s=0;y.addEventListener("touchstart",o=>{e=o.touches[0].clientX}),y.addEventListener("touchend",o=>{s=o.changedTouches[0].clientX;const l=e-s;Math.abs(l)>50&&(l>0?a=(a+1)%d.length:a=(a-1+d.length)%d.length,g(a))})}document.addEventListener("DOMContentLoaded",function(){const e=new URLSearchParams(window.location.search);function s(n,r,u){const p=new Date;p.setTime(p.getTime()+u*24*60*60*1e3),document.cookie=`${n}=${encodeURIComponent(r)}; expires=${p.toUTCString()}; path=/`}function o(n){const u=`; ${document.cookie}`.split(`; ${n}=`);if(u.length===2)return decodeURIComponent(u.pop().split(";").shift())}if(e.toString()){const n="?"+e.toString(),r=o("utm_params");n!==r&&s("utm_params",n,7)}function l(n){return btoa(n).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}function t(n){n.preventDefault();let r=o("utm_params")||"";if(!r){window.open("https://t.me/Event_Shelest_bot","_blank");return}let u=l(r);if(u.length>64){const h=new URLSearchParams(r.replace(/^\?/,"")),b=new URLSearchParams;h.has("utm_source")&&b.set("utm_source",h.get("utm_source")),h.has("utm_medium")&&b.set("utm_medium",h.get("utm_medium")),r="?"+b.toString(),u=l(r)}const p=`https://t.me/Event_Shelest_bot?start=${u}`;window.open(p,"_blank")}document.querySelectorAll('a[href*="t.me/Event_Shelest_bot"]').forEach(n=>{n.addEventListener("click",t)})});
//# sourceMappingURL=index.js.map
