import{S as j,N as v}from"./assets/vendor-VH5JPVsm.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const b=document.querySelector(".js-btn-burger-menu"),h=document.querySelector(".js-close-menu"),p=document.querySelector(".js-burger-menu"),L=document.querySelectorAll(".js-menu-link"),q=document.querySelector(".js-logo");function E(){p.classList.add("active"),p.style.visibility="visible",document.body.classList.add("no-scroll")}function u(){p.classList.remove("active"),document.body.classList.remove("no-scroll"),setTimeout(()=>{p.style.visibility="hidden"},300)}b.addEventListener("click",E);h.addEventListener("click",u);document.addEventListener("click",e=>{!p.contains(e.target)&&!b.contains(e.target)&&u()});document.addEventListener("keydown",e=>{e.key==="Escape"&&u()});L.forEach(e=>{e.addEventListener("click",u)});q.addEventListener("click",u);document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("gallery-container"),l=10,r="gallery/thumbs/",c="gallery/full/",t=".jpeg";for(let n=1;n<=l;n++){const s=document.createElement("div");s.classList.add("swiper-slide");const d=document.createElement("a");d.href=`${c}${n}${t}`,d.setAttribute("data-fancybox","gallery"),d.setAttribute("data-caption",`foto ${n}`);const m=document.createElement("img");m.src=`${r}${n}${t}`,m.alt=`Gallery imeges ${n}`,d.appendChild(m),s.appendChild(d),e.appendChild(s)}new j(".mySwiper",{loop:!0,slidesPerView:1,spaceBetween:10,pagination:!1,speed:800,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},autoplay:{delay:3e3,disableOnInteraction:!1},breakpoints:{1440:{slidesPerView:3,spaceBetween:30}}}),v.bind("[data-fancybox='gallery']",{})});const S={big:{title:"ВЕЛИКИЙ РЕСТОРАН",info:`
      <p>290 м², до 120 гостей</p>`,text:"Велика зала з гримеркою, баром, простором для сцени, танців і банкету.",capacity:{theatre:"100 гостей",classroom:"60 гостей",conference:"40 гостей",uShape:"50 гостей",banquet:"80 гостей"},images:["./big/1.jpg","./big/2.jpg","./big/3.jpg","./big/4.jpg","./big/5.jpg","./big/6.jpg"]},small:{title:"МАЛИЙ РЕСТОРАН",info:`
      <p>180 м², до 60 гостей</p>
    `,text:"Зала з гримеркою, баром, каміном, терасою та зоною для нетворкінгу біля вогнища.",capacity:{theatre:"60 гостей",classroom:"40 гостей",conference:"36 гостей",uShape:"30 гостей",banquet:"50 гостей"},images:["./small/1.jpg","./small/2.jpg","./small/3.jpg","./small/4.jpg","./small/5.jpg","./small/6.jpg"]},banquetroom:{title:"БАНКЕТНА КІМНАТА",info:`
      <p>50 м², до 25 гостей</p>
    `,text:"Закрита частина ресторану з окремим входом, терасою та зоною для вечірнього багаття.",capacity:{theatre:"30 гостей",classroom:"20 гостей",conference:"25 гостей",uShape:"15 гостей",banquet:"25 гостей"},images:["./banquet/1.jpg","./banquet/2.jpg","./banquet/3.jpg","./banquet/4.jpg","./banquet/5.jpg","./banquet/6.jpg"]},lobi:{title:"ЛОБІ ГОТЕЛЮ",info:`
      <p>160 м², до 50 гостей</p>
    `,text:"Ми повністю закриваємо крило готелю, щоб нічого не відволікало гостей від події.",capacity:{theatre:"50 гостей",banquet:"30 гостей"},images:["./lobi/1.jpg","./lobi/2.jpg","./lobi/3.jpg","./lobi/4.jpg","./lobi/5.jpg"]},pool:{title:"БАСЕЙН У ЛІСІ",info:`
      <p>площа палуби — 4500 м², до 300 гостей</p>
    `,text:"Великий басейн з видом на річку та ліс, власним баром, екраном для презентацій або кіно.",images:["./pool/1.jpg","./pool/2.jpg","./pool/3.jpg","./pool/4.jpg","./pool/5.jpg","./pool/6.jpg","./pool/7.jpg"]},terrasa:{title:"ТЕРАСА НАД ВОДОЮ",info:`
      <p>240 м², до 60 гостей</p>
    `,text:"Затишна локація з видом на ліс і річку для естетичних банкетів або для активного відпочинку на каяках, cапах чи катері.",capacity:{theatre:"40 гостей",conference:"25 гостей",banquet:"50 гостей"},images:["./terrasa/1.jpg","./terrasa/2.jpg","./terrasa/3.jpg","./terrasa/4.jpg"]}},o=document.getElementById("location-modal"),f=o.querySelector(".slider"),x=o.querySelector(".modal-title"),k=o.querySelector(".modal-info"),w=o.querySelector(".modal-text"),y=o.querySelector(".modal-capacity");let a=[],i=0;function $(e){return{theatre:"Theatre",classroom:"Classroom",conference:"Conference",uShape:"U-shape",banquet:"Banquet"}[e]||e}document.querySelectorAll(".btn-location").forEach(e=>{e.addEventListener("click",()=>{const l=e.closest("li").dataset.location,r=S[l];r&&(x.textContent=r.title,k.innerHTML=r.info,w.textContent=r.text,r.capacity?y.innerHTML=Object.entries(r.capacity).map(([c,t])=>`
          <p><strong>${$(c)}:</strong> ${t}</p>
        `).join(""):y.innerHTML="",f.innerHTML=r.images.map((c,t)=>`<div class="slide ${t===0?"active":""}">
          <img src="${c}" alt="${r.title} фото ${t+1}" />
        </div>`).join(""),a=f.querySelectorAll(".slide"),i=0,o.classList.add("active"))})});o.querySelector(".modal-close").addEventListener("click",()=>{o.classList.remove("active")});o.addEventListener("click",e=>{e.target===o&&o.classList.remove("active")});document.addEventListener("keydown",e=>{o.classList.contains("active")&&(e.key==="ArrowRight"&&(i=(i+1)%a.length,g(i)),e.key==="ArrowLeft"&&(i=(i-1+a.length)%a.length,g(i)),e.key==="Escape"&&o.classList.remove("active"))});const g=e=>{a.forEach(l=>l.classList.remove("active")),a[e].classList.add("active")};o.querySelector(".next").addEventListener("click",()=>{a.length&&(i=(i+1)%a.length,g(i))});o.querySelector(".prev").addEventListener("click",()=>{a.length&&(i=(i-1+a.length)%a.length,g(i))});
//# sourceMappingURL=index.js.map
