import{S as h,N as v}from"./assets/vendor-VH5JPVsm.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const b=document.querySelector(".js-btn-burger-menu"),L=document.querySelector(".js-close-menu"),u=document.querySelector(".js-burger-menu"),j=document.querySelectorAll(".js-menu-link"),E=document.querySelector(".js-logo");function S(){u.classList.add("active"),u.style.visibility="visible",document.body.classList.add("no-scroll")}function g(){u.classList.remove("active"),document.body.classList.remove("no-scroll"),setTimeout(()=>{u.style.visibility="hidden"},300)}b.addEventListener("click",S);L.addEventListener("click",g);document.addEventListener("click",e=>{!u.contains(e.target)&&!b.contains(e.target)&&g()});document.addEventListener("keydown",e=>{e.key==="Escape"&&g()});j.forEach(e=>{e.addEventListener("click",g)});E.addEventListener("click",g);document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("gallery-container"),r=10,n="gallery/thumbs/",a="gallery/full/",t=".jpeg";for(let o=1;o<=r;o++){const l=document.createElement("div");l.classList.add("swiper-slide");const d=document.createElement("a");d.href=`${a}${o}${t}`,d.setAttribute("data-fancybox","gallery"),d.setAttribute("data-caption",`foto ${o}`);const f=document.createElement("img");f.src=`${n}${o}${t}`,f.alt=`Gallery imeges ${o}`,d.appendChild(f),l.appendChild(d),e.appendChild(l)}new h(".mySwiper",{loop:!0,slidesPerView:1,spaceBetween:10,pagination:!1,speed:800,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},autoplay:{delay:3e3,disableOnInteraction:!1},breakpoints:{1280:{slidesPerView:3,spaceBetween:30}}}),v.bind("[data-fancybox='gallery']",{})});const q={big:{title:"ВЕЛИКИЙ РЕСТОРАН",info:`
      <p>290 м², до 120 гостей</p>`,text:"Велика зала з гримеркою, баром, простором для сцени, танців і банкету.",capacity:{theatre:"100 гостей",classroom:"60 гостей",conference:"40 гостей",uShape:"50 гостей",banquet:"80 гостей"},images:["./big/1.jpg","./big/2.jpg","./big/3.jpg","./big/4.jpg","./big/5.jpg","./big/6.jpg"]},small:{title:"МАЛИЙ РЕСТОРАН",info:`
      <p>180 м², до 60 гостей</p>
    `,text:"Зала з гримеркою, баром, каміном, терасою та зоною для нетворкінгу біля вогнища.",capacity:{theatre:"60 гостей",classroom:"40 гостей",conference:"36 гостей",uShape:"30 гостей",banquet:"50 гостей"},images:["./small/1.jpg","./small/2.jpg","./small/3.jpg","./small/4.jpg","./small/5.jpg","./small/6.jpg"]},banquetroom:{title:"БАНКЕТНА КІМНАТА",info:`
      <p>50 м², до 25 гостей</p>
    `,text:"Закрита частина ресторану з окремим входом, терасою та зоною для вечірнього багаття.",capacity:{theatre:"30 гостей",classroom:"20 гостей",conference:"25 гостей",uShape:"15 гостей",banquet:"25 гостей"},images:["./banquet/1.jpg","./banquet/2.jpg","./banquet/3.jpg","./banquet/4.jpg","./banquet/5.jpg","./banquet/6.jpg"]},lobi:{title:"ЛОБІ ГОТЕЛЮ",info:`
      <p>160 м², до 50 гостей</p>
    `,text:"Ми повністю закриваємо крило готелю, щоб нічого не відволікало гостей від події.",capacity:{theatre:"50 гостей",banquet:"30 гостей"},images:["./lobi/1.jpg","./lobi/2.jpg","./lobi/3.jpg","./lobi/4.jpg","./lobi/5.jpg"]},pool:{title:"БАСЕЙН У ЛІСІ",info:`
      <p>площа палуби — 4500 м², до 300 гостей</p>
    `,text:"Великий басейн з видом на річку та ліс, власним баром, екраном для презентацій або кіно.",images:["./pool/1.jpg","./pool/2.jpg","./pool/3.jpg","./pool/4.jpg","./pool/5.jpg","./pool/6.jpg","./pool/7.jpg"]},terrasa:{title:"ТЕРАСА НАД ВОДОЮ",info:`
      <p>240 м², до 60 гостей</p>
    `,text:"Затишна локація з видом на ліс і річку для естетичних банкетів або для активного відпочинку на каяках, cапах чи катері.",capacity:{theatre:"40 гостей",conference:"25 гостей",banquet:"50 гостей"},images:["./terrasa/1.jpg","./terrasa/2.jpg","./terrasa/3.jpg","./terrasa/4.jpg"]}},s=document.getElementById("location-modal"),m=s.querySelector(".slider"),w=s.querySelector(".modal-title"),k=s.querySelector(".modal-info"),x=s.querySelector(".modal-text"),y=s.querySelector(".modal-capacity");let c=[],i=0;function $(e){return{theatre:"Theatre",classroom:"Classroom",conference:"Conference",uShape:"U-shape",banquet:"Banquet"}[e]||e}document.querySelectorAll(".btn-location").forEach(e=>{e.addEventListener("click",()=>{const r=e.closest("li").dataset.location,n=q[r];n&&(w.textContent=n.title,k.innerHTML=n.info,x.textContent=n.text,n.capacity?y.innerHTML=Object.entries(n.capacity).map(([a,t])=>`<p><strong>${$(a)}:</strong> ${t}</p>`).join(""):y.innerHTML="",m.innerHTML=n.images.map((a,t)=>`<div class="slide ${t===0?"active":""}">
            <img src="${a}" alt="${n.title} фото ${t+1}" />
          </div>`).join(""),c=m.querySelectorAll(".slide"),i=0,s.classList.add("active"),M())})});s.querySelector(".modal-close").addEventListener("click",()=>{s.classList.remove("active")});s.addEventListener("click",e=>{e.target===s&&s.classList.remove("active")});const p=e=>{c.forEach(r=>r.classList.remove("active")),c[e].classList.add("active")};s.querySelector(".next").addEventListener("click",()=>{c.length&&(i=(i+1)%c.length,p(i))});s.querySelector(".prev").addEventListener("click",()=>{c.length&&(i=(i-1+c.length)%c.length,p(i))});document.addEventListener("keydown",e=>{s.classList.contains("active")&&(e.key==="ArrowRight"&&(i=(i+1)%c.length,p(i)),e.key==="ArrowLeft"&&(i=(i-1+c.length)%c.length,p(i)),e.key==="Escape"&&s.classList.remove("active"))});function M(){let e=0,r=0;m.addEventListener("touchstart",n=>{e=n.touches[0].clientX}),m.addEventListener("touchend",n=>{r=n.changedTouches[0].clientX;const a=e-r;Math.abs(a)>50&&(a>0?i=(i+1)%c.length:i=(i-1+c.length)%c.length,p(i))})}document.addEventListener("DOMContentLoaded",function(){const e=new URLSearchParams(window.location.search);e.toString()&&sessionStorage.setItem("utm_params","?"+e.toString());function r(a){return btoa(a).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}const n=document.querySelector(".telegram-bot");n&&n.addEventListener("click",function(a){a.preventDefault();const t=sessionStorage.getItem("utm_params")||"";if(!t){window.open("https://t.me/Event_Shelest_bot","_blank");return}const d=`https://t.me/Event_Shelest_bot?start=${r(t).slice(0,64)}`;console.log("Telegram link:",d),window.open(d,"_blank")})});
//# sourceMappingURL=index.js.map
